# Generated by Django 3.0.2 on 2020-03-10 18:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_account', '0002_remove_profile_privilege_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('business', 'BUSINESS'), ('credit_card', 'CREDIT_CARD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('business', 'BUSINESS')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
