# Generated by Django 3.0.2 on 2020-03-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0003_auto_20200310_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
