# Generated by Django 3.0.2 on 2020-03-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0004_remove_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('checking', 'CHECKING'), ('credit_card', 'CREDIT_CARD')], max_length=20),
        ),
    ]
