# Generated by Django 3.0.2 on 2020-03-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0005_auto_20200318_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_name',
        ),
    ]
