# Generated by Django 3.0.2 on 2020-03-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0006_remove_profile_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
