# Generated by Django 3.0.2 on 2020-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200322_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_status', models.CharField(choices=[('TIER1', 'TIER1'), ('TIER2', 'TIER2'), ('TIER3', 'TIER3')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=3352859148, max_length=10, unique=True),
        ),
    ]
