# Generated by Django 3.0.2 on 2020-03-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200325_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=3747183377, max_length=10, unique=True),
        ),
    ]
