# Generated by Django 3.0.2 on 2020-03-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_tiers'),
        ('home', '0026_auto_20200325_1412'),
    ]

    operations = [
    ]
